/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/tests.check" instead.
 */

#include <check.h>
#include <stdio.h>

#include "../solve_equation/solve_equation.h"

START_TEST(solve_equation1) {
  // a = 0, b = 0, c = 0; infinity test
  quadraticRoots temp;
  temp = solve_equation(0, 0, 0);
  ck_assert_double_eq(temp.roots_num, -1);
}
END_TEST

START_TEST(solve_equation2) {
  // a = 0, b = 2, c = 1; linear test 1
  quadraticRoots temp;
  temp = solve_equation(0, 2, 1);
  ck_assert_double_eq(temp.roots_num, 1);
  ck_assert_double_eq(temp.root1, -0.5);
}
END_TEST

START_TEST(solve_equation3) {
  // a = 0, b = 3, c = 0; linear test 2
  quadraticRoots temp;
  temp = solve_equation(0, 3, 0);
  ck_assert_double_eq(temp.roots_num, 1);
  ck_assert_double_eq(temp.root1, 0);
}
END_TEST

START_TEST(solve_equation4) {
  // a = 1, b = -5, c = 6; quadratic test 1
  quadraticRoots temp;
  temp = solve_equation(1, -5, 6);
  ck_assert_double_eq(temp.roots_num, 2);
  ck_assert_double_eq(temp.root1, 3);
  ck_assert_double_eq(temp.root2, 2);
}
END_TEST

START_TEST(solve_equation5) {
  // a = 1, b = -4, c = 4; quadratic test 2
  quadraticRoots temp;
  temp = solve_equation(1, -4, 4);
  ck_assert_double_eq(temp.roots_num, 1);
  ck_assert_double_eq(temp.root1, 2);
}
END_TEST

START_TEST(solve_equation6) {
  // a = 1, b = 0, c = -9; quadratic test 3
  quadraticRoots temp;
  temp = solve_equation(1, 0, -9);
  ck_assert_double_eq(temp.roots_num, 2);
  ck_assert_double_eq(temp.root1, 3);
  ck_assert_double_eq(temp.root2, -3);
}
END_TEST

START_TEST(solve_equation7) {
  // a = 1, b = 2, c = 1; discriminant is zero, one root
  quadraticRoots temp;
  temp = solve_equation(1, 2, 1);
  ck_assert_double_eq(temp.roots_num, 1);
  ck_assert_double_eq(temp.root1, -1);
}
END_TEST

START_TEST(solve_equation8) {
  // a = 1, b = 0, c = 1; discriminant is less than zero, no real roots
  quadraticRoots temp;
  temp = solve_equation(1, 0, 1);
  ck_assert_double_eq(temp.roots_num, 0);
}
END_TEST

START_TEST(solve_equation9) {
  // a = 1, b = 1, c = 1; discriminant is less than zero, no real roots
  quadraticRoots temp;
  temp = solve_equation(1, 1, 1);
  ck_assert_double_eq(temp.roots_num, 0);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, solve_equation1);
  tcase_add_test(tc1_1, solve_equation2);
  tcase_add_test(tc1_1, solve_equation3);
  tcase_add_test(tc1_1, solve_equation4);
  tcase_add_test(tc1_1, solve_equation5);
  tcase_add_test(tc1_1, solve_equation6);
  tcase_add_test(tc1_1, solve_equation7);
  tcase_add_test(tc1_1, solve_equation8);
  tcase_add_test(tc1_1, solve_equation9);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
